# Generated by Django 3.2.10 on 2022-01-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0007_homepagecarrouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarrouselimages',
            name='carousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
